name: Close all issues

on:
  workflow_dispatch: # Manual triggering

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Close Issues
        run: |
          # Fetch all open issues
          ISSUES=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | \
          jq -r '.[].number')

          # Loop through and close each issue
          for issue in $ISSUES
          do
            curl -s -X POST \
              -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue/comments" \
              --data '{"body":"This issue has been closed by a GitHub Action."}'

            curl -s -X PATCH \
              -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue" \
              --data '{"state":"closed"}'
          done
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
