name: "Create Bot Website"

on:
  issues:
    types: [opened]

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
    
      # Examples on how to use the output
      - name: Show parsed payload data
        run: |
          echo '${{ steps.parse.outputs.payload }}'
          
          # Set the parsed data as an environment variable
          echo "::set-env name=PARSED_PAYLOAD::${{ steps.parse.outputs.payload }}"
      
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Name: ${{ fromJson(env.PARSED_PAYLOAD).Name }}
            ID: ${{ fromJson(env.PARSED_PAYLOAD).ID }}
            Support: ${{ fromJson(env.PARSED_PAYLOAD).Support }}
            Description: ${{ fromJson(env.PARSED_PAYLOAD).Description }}
          reactions: '+1'
