name: "Create Bot Website"

on:
  issues:
    types: [opened]

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
    
      # Examples on how to use the output
      - name: Show parsed payload data
        run: |
          echo '${{ steps.parse.outputs.payload }}'
          
          echo '${{ fromJson(steps.parse.outputs.payload).Name }}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.generate-html.outputs.html }}
          reactions: '+1'
