name: "Create Bot Website"

on:
  issues:
    types: [opened]

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
    
      # Examples on how to use the output
      - name: Show parsed payload data
        run: |
          echo '${{ steps.parse.outputs.payload }}'
          
          echo '${{ fromJson(steps.parse.outputs.payload).Name }}'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create HTML file
        run: |
          cat <<EOF > ${{ fromJson(steps.parse.outputs.payload).Name }}.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>${{ fromJson(steps.parse.outputs.payload).Name }}</title>
            <link rel="stylesheet" type="text/css" href="style.css">
            <link rel="icon" href="${{ fromJson(steps.parse.outputs.payload).Icon }}" type="image/x-icon">
          </head>
          <body>
            <div class="container">
              <header>
                <img src="${{ fromJson(steps.parse.outputs.payload).Icon }}" alt="Bot Logo" id="bot-logo">
                <h1 id="bot-name">${{ fromJson(steps.parse.outputs.payload).Name }}</h1>
              </header>
              
              <section class="description">
                <p>${{ fromJson(steps.parse.outputs.payload).Description }}</p>
              </section>
              <br>
              
              <section class="support">
                <p>For support and discussions, join our Discord server: <a href="${{ fromJson(steps.parse.outputs.payload).Invite }}" target="_blank">Join the server</a></p>
              </section>
              <br>
              <section class="bot-demo">
                <img src="${{ fromJson(steps.parse.outputs.payload).Demo }}" alt="Bot Demo" id="bot-image">
              </section>
              <section class="footer">
                <p>This website was generated for free by <a href="#" target="_blank">guardian bot list!</a> You can make one for your bot at <a href="https://github.com/adambotfd/dashboard-maker/" target="_blank">our github repo</a> or advertise your discord bot <a href="https://guardianbots.vercel.app" target="_blank">here.</a></p>
            </section>
            </div>
          </body>
          </html>
          EOF

      - name: Display file content
        run: cat ${{ fromJson(steps.parse.outputs.payload).Name }}.html

      - name: Configure Git
        run: |
          git config --local user.email "multibotfd@gmail.com"
          git config --local user.name "adambotfd"

      - name: Add and commit changes
        run: |
          git add ${{ fromJson(steps.parse.outputs.payload).Name }}.html
          git commit -m "Add ${{ fromJson(steps.parse.outputs.payload).Name }}.html"

      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: main
          github_token: ${{ secrets.PAT_TOKEN }}
