name: "Create Bot Website"
description: Create a website for your bot super easily with no coding experience
on:
  issues:
    types: [opened]

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Generate HTML
        id: generate-html
        run: |
          echo "::set-output name=html::<html><body><h1>Bot Website</h1><p>Bot ID: ${{ github.event.issue.body.id }}</p><p>Bot Name: ${{ github.event.issue.body.name }}</p><p>Bot Description: ${{ github.event.issue.body.description }}</p><p>Support Server: <a href='${{ github.event.issue.body.support }}'>Support Server</a></p></body></html>"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.generate-html.outputs.html }}
          reactions: '+1'
