name: "Create Bot Website"

on:
  issues:
    types: [opened]

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
    
      # Examples on how to use the output
      - name: Show parsed payload data
        run: |
          echo '${{ steps.parse.outputs.payload }}'
          
          echo '${{ fromJson(steps.parse.outputs.payload).Name }}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Follow these instructions to Finnish up with your website!

            1. Create a file in the main directory of this repository with the name `${{ fromJson(steps.parse.outputs.payload).Name }}.html`!
            2. Put the following content into the file:
            ```
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>${{ fromJson(steps.parse.outputs.payload).Name }}</title>
              <link rel="stylesheet" type="text/css" href="style.css">
              <link rel="icon" href="${{ fromJson(steps.parse.outputs.payload).Icon }}" type="image/x-icon">
            </head>
            <body>
              <div class="container">
                <header>
                  <img src="${{ fromJson(steps.parse.outputs.payload).Icon }}" alt="Bot Logo" id="bot-logo">
                  <h1 id="bot-name">${{ fromJson(steps.parse.outputs.payload).Name }}</h1>
                </header>
                
                <section class="description">
                  <p>${{ fromJson(steps.parse.outputs.payload).Description }}</p>
                </section>
                <br>
                
                <section class="support">
                  <p>For support and discussions, join our Discord server: <a href="${{ fromJson(steps.parse.outputs.payload).Invite }}" target="_blank">Join the server</a></p>
                </section>
                <br>
                <section class="bot-demo">
                  <img src="${{ fromJson(steps.parse.outputs.payload).Demo }}" alt="Bot Demo" id="bot-image">
                </section>
              </div>
            </body>
            </html>
            ```
            3. Finally, submit the pull request and our team will handle the rest!

          reactions: '+1'
