name: Update Sitemap

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Sitemap
        run: |
          input_string=$(curl -s https://guardianapi.vercel.app/botlist/10000000000)
          bot_ids=$(echo "$input_string" | grep -oP '"bot_ids":\s*\[\K[^\]]+')
          for bot_id in $bot_ids; do
            echo "Processing bot ID: $bot_id"
            echo "  <url>"
            echo "    <loc>https://guardianbots.vercel.app/$bot_id</loc>"
            echo "  </url>"
          done >> sitemap.xml

          echo '</urlset>' >> sitemap.xml

      - name: Commit and push changes
        run: |
          git config --local user.email "multibotfd@gmail.com"
          git config --local user.name "adambotfd"
          git add sitemap.xml
          git commit -m "Update sitemap.xml (Automatic)"
          git push
