name: Update Sitemap

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' > sitemap.xml

          # Add URLs from the root directory
          find . -type f -name "*.html" | sed 's|^./||' | while read -r line; do
            echo "  <url>"
            echo "    <loc>https://disforge.vercel.app/$line</loc>"
            echo "  </url>"
          done >> sitemap.xml

          echo '</urlset>' >> sitemap.xml

      - name: Commit and push changes
        run: |
          git config --local user.email "multibotfd@gmail.com"
          git config --local user.name "adambotfd"
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push
